/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cover_jvm_jdk_classes_sun_misc_Unsafe */

#ifndef _Included_com_cover_jvm_jdk_classes_sun_misc_Unsafe
#define _Included_com_cover_jvm_jdk_classes_sun_misc_Unsafe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cover_jvm_jdk_classes_sun_misc_Unsafe
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_cover_jvm_jdk_classes_sun_misc_Unsafe_allocateMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_cover_jvm_jdk_classes_sun_misc_Unsafe
 * Method:    allocateObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_cover_jvm_jdk_classes_sun_misc_Unsafe_allocateObject
  (JNIEnv *, jclass);

/*
 * Class:     com_cover_jvm_jdk_classes_sun_misc_Unsafe
 * Method:    initMemoryModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cover_jvm_jdk_classes_sun_misc_Unsafe_initMemoryModel
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
