/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cover_jvm_jdk_classes_JniEnv */

#ifndef _Included_com_cover_jvm_jdk_classes_JniEnv
#define _Included_com_cover_jvm_jdk_classes_JniEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cover_jvm_jdk_classes_JniEnv
 * Method:    getMethodID
 * Signature: (Lcom/cover/jvm/jdk/classes/Handle;Ljava/lang/String;Ljava/lang/String;)Lcom/cover/jvm/jdk/classes/Handle;
 */
JNIEXPORT jobject JNICALL Java_com_cover_jvm_jdk_classes_JniEnv_getMethodID
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     com_cover_jvm_jdk_classes_JniEnv
 * Method:    CallStaticVoidMethod
 * Signature: (Lcom/cover/jvm/jdk/classes/Handle;Lcom/cover/jvm/jdk/classes/Handle;)V
 */
JNIEXPORT void JNICALL Java_com_cover_jvm_jdk_classes_JniEnv_CallStaticVoidMethod
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
