/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cover_jvm_jdk_classes_Threads */

#ifndef _Included_com_cover_jvm_jdk_classes_Threads
#define _Included_com_cover_jvm_jdk_classes_Threads
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cover_jvm_jdk_classes_Threads
 * Method:    createVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cover_jvm_jdk_classes_Threads_createVM
  (JNIEnv *, jclass);

/*
 * Class:     com_cover_jvm_jdk_classes_Threads
 * Method:    gc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cover_jvm_jdk_classes_Threads_gc
  (JNIEnv *, jclass);

/*
 * Class:     com_cover_jvm_jdk_classes_Threads
 * Method:    fullGc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cover_jvm_jdk_classes_Threads_fullGc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
