/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cover_jvm_jdk_classes_sun_misc_AppClassLoader */

#ifndef _Included_com_cover_jvm_jdk_classes_sun_misc_AppClassLoader
#define _Included_com_cover_jvm_jdk_classes_sun_misc_AppClassLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cover_jvm_jdk_classes_sun_misc_AppClassLoader
 * Method:    loadKlass
 * Signature: (Ljava/lang/String;)Lcom/cover/jvm/jdk/classes/Handle;
 */
JNIEXPORT jobject JNICALL Java_com_cover_jvm_jdk_classes_sun_misc_AppClassLoader_loadKlass
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
